name: Testing setup script

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [bookworm, bullseye]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-qemu-action@v1

    - name: Test script on Debian ${{ matrix.os }}
      run: docker run --rm -v $PWD:/mnt -w /mnt debian:${{ matrix.os }} /bin/bash -c 'chmod +x setup.sh && ./setup.sh'
